2025-04-29 20:47:37,909:INFO:logging in using static token
2025-04-29 20:47:38,967:INFO:Shard ID None has connected to Gateway (Session ID: 400d7c1212158cafd09be9b362460633).
2025-04-29 20:47:41,204:ERROR:An error occurred in event: on_ready
2025-04-29 20:47:41,205:ERROR:Error details:
Traceback (most recent call last):
  File "/var/data/python/lib/python3.12/site-packages/discord/client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "/home/imafella/Coding Projects/discord_banker_bot/Testybot.py", line 52, in on_ready
    await client.get_channel(main_entry_channel).send("I am now online!")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'

